import React from 'react'
import mecimg from "./assests/MECHANICAL-ENGINEERING-1.webp"
import adminimg from "./assests/admission-img-1.png"

const Mec = () => {
  return (
    <div className='container-fluid'>
        <img src={mecimg} alt="" className='w-100'/>
        <div className='row'>
            <div className='col-12 col-lg-4'>
                <h5>Mechanical Engineering</h5>
                <h5>About Department</h5>
                <h5>Vision</h5>
                <h5>Infrastructure</h5>
                <h5>Board Of Study</h5>
                <h5>AchieveMents</h5>
                <h5>Innovative Teaching and Learning</h5>
                <img src={adminimg} alt="" className='w-100'/>
                <h4>2025
Admission
Now Open</h4>
            </div>
            <div className='col-12 col-lg-8'>
                <strong>About the Department</strong>
                <p>
                    Department of Mechanical Engineering is the one of oldest and broadest among the engineering disciplines. This programme is concerned with the principles of force, energy and motion; this program encompasses the elements of aerospace, electrical, civil, chemical and even material science and bio-engineering along with physics and mathematics. Core subjects such as material science, metallurgy, solid and fluid mechanics, thermodynamics, heat transfer, control, product design and manufacturing processes provide the confidence, ability and flexibility to work in various industries of repute. Mechanical engineers use their knowledge of design, manufacture, and operational processes to advance the world around us, enhancing safety, economic vitality and enjoyment throughout the world. Mechanical engineering is the study of design, development, construction, and testing of mechanical and thermal sensors and devices, including tools, engines, and machines. It focuses the subject which includes automobile engineering, manufacturing engineering, power plant engineering, thermal engineering, and mechatronics engineering etc. Mechanical engineering is the career center on creating technologies to meet a wide range of human needs. It has roots in the industrial revolution with the advent of the steam engine, automated manufacturing, and the demands of rail, road transportation requiring increasingly innovative and sophisticated engineering solutions. Mechanical engineers work mostly in engineering services, research and development, and manufacturing.Mechanical engineers work with nature and constitute typically the following task: Understand real-time problems in-depth, analyze and provide viable solution for the problems in the field of manufacturing, thermal and allied fields using modern tools such as, Computer Aided Engineering (CAE), 2D, 3D modeling, solid modeling generated by Computer Aided Design (CAD) in better and easier way. Finite Element Analysis (FEA), Computational Fluid Dynamics (CFD), Digital Manufacturing, Computer Aided Manufacturing (CAM) and Computer Integrated Manufacturing (CIM) are the major technological tools widely used to provide the optimal solution for the real time problems of the industry. In addition, the tool such as Product Lifecycle Management (PLM) is practiced in modern industries in order to manage the entire lifecycle of the product.The allied fields such as Robotics, Automation, Reverse Engineering, Industrial Ergonomics, Tribology, Mechanical Instrumentation, Aero modeling & maintenance, Textile and Leather machinery manufacturing and maintenance etc are the major focus areas of mechanical engineering where they have lot of career opportunity.
                </p>
                <div class="card">
                    
                    <div class="card-body">
                        <h4 class="card-title"><span className='text-primary'>The role of Mechanical Engineers falls in any one the following category</span></h4>
                        
                        <ul>
                            <li>Design and develop software application for different industries</li>
                            <li>Manages the software, hardware & networks in any industry</li>
                            <li>Involves in the design and development of the hardware components of PCs & laptops</li>
                            <li>Develop software for peripheral computing devices such as printers, modems and scanners</li>
                            <li>Writes code and algorithms for operating systems like Windows, Linux etc.</li>
                        </ul>
                    </div>
                </div>
                <br></br>
                <div class="card">
                    
                    <div class="card-body">
                        <h4 class="card-title"><span className='text-danger'>Mechanical Engineer can work in wide range of fields from the following categories</span></h4>

                        <ul>
                            <li>In Government for Engineering services, Remote sensing, E-Governance, etc.</li>
                            <li>In PSU`s like EDP officers in Banking sectors, Railways, Airport Authorities of India, ONGC and Petroleum Corporations, etc.</li>
                            <li>In Core Sectors like Tata Consultancy Services, Infosys, Virtusa, IBM, Cognizant Technologies, Zoho Coorporation, Vodafone, Rapid-I, Revature, etc.</li>
                            <li>In Private Sectors as Business Development Associates, Content Development Manager, Financial Advisor and Consultant, etc.</li>
                            <li>It also provide the opportunities and eligibility to write UPSC – IES (Indian Engineering Services)</li>
                        </ul>
                    </div>
                </div>
                <br></br>
                <p>
                    <span className='text-primary'>The Department of Mechanical and Business System exists since the inception of the institution, in the year 2020. The department offers the following courses</span>
                </p>
                <p>
                    4 year Undergraduate ProgrammeB.Tech., – Mechanical and Business System60 Intake The Department has excellent infrastructure in terms of laboratories, classrooms, seminar hall, Centre of Excellence, etc. The department laboratories are interconnected through a well-designed seamless network with Internet facility with the speed of 155 Mbps to facilitate the student’s access to web resources. This helps the students in meeting the demands of the regular curriculum and latest technology needs. With the co-operation and involvement of the dedicated team of well-qualified faculty members, the department constantly strives to improve its academic standards. Our students involve in developing the solutions for real time industrial problems and participate in national level and international level competitions and brought laurel to the department
                </p>
                

                </div>
        </div>

    </div>
  )
}

export default Mec